# -*- coding: utf-8 -*-
"""streamlitEye.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hl3LH5Y6QSvTgSnZzvdt0JlYVkiO9LYz
"""

import streamlit as st
from tensorflow.keras.models import load_model
from PIL import Image
import numpy as np

model = load_model(r'C:\Users\91733\OneDrive\Desktop\Final Project\Project4_Eye_Disease_Dataset\my_model.keras', compile=False)

label_mapping = {
    0: 'cataract',
    1: 'diabetic_retinopathy',
    2: 'glaucoma',
    3: 'normal'
}

def preprocess_image(image):
    img = image.resize((256, 256))
    img = np.array(img) / 255.0
    img = np.expand_dims(img, axis=0)
    return img

st.title("Eye Disease Image Classification using Keras")
uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])
if uploaded_file is not None:
    image = Image.open(uploaded_file)
    display_width = 300

    st.image(image, caption='Uploaded Image.', use_column_width=False, width=display_width)
    st.write("")
    st.write("Classifying...")

    img = preprocess_image(image)
    predictions = model.predict(img)
    predicted_class = np.argmax(predictions, axis=1)[0]
    predicted_label = label_mapping[predicted_class]

    st.write(f'Predicted Class: {predicted_class} - {predicted_label}')